# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secret',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='secret',
            name='secret_user',
        ),
    ]
